version: '3'

services:
  video-downloader:
    build: .
    container_name: video-downloader
    restart: always
    ports:
      - "3000:3000"
    networks:
      - npm_default
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 768M
        reservations:
          memory: 256M

networks:
  npm_default:
    external: true 